In [3]:
import pandas as pd

In [4]:
import pandas as pd

data = {
    "Student": ["Aarav", "Ananya", "Rahul", "Priya"],
    "Python": [85, 76, 65, 92],
    "Math": [90, 88, 70, 95],
    "DBMS": [78, 91, 68, 89]
}

df = pd.DataFrame(data)

print(df)

  Student  Python  Math  DBMS
0   Aarav      85    90    78
1  Ananya      76    88    91
2   Rahul      65    70    68
3   Priya      92    95    89

In [5]:
df["Python"]

0    85
1    76
2    65
3    92
Name: Python, dtype: int64

In [6]:
df.shape

(4, 4)

In [7]:
df.describe

<bound method NDFrame.describe of   Student  Python  Math  DBMS
0   Aarav      85    90    78
1  Ananya      76    88    91
2   Rahul      65    70    68
3   Priya      92    95    89>

In [8]:
df.info

<bound method DataFrame.info of   Student  Python  Math  DBMS
0   Aarav      85    90    78
1  Ananya      76    88    91
2   Rahul      65    70    68
3   Priya      92    95    89>

In [9]:
df.head()

  Student  Python  Math  DBMS
0   Aarav      85    90    78
1  Ananya      76    88    91
2   Rahul      65    70    68
3   Priya      92    95    89

In [10]:
df.columns

Index(['Student', 'Python', 'Math', 'DBMS'], dtype='str')

In [11]:
df.describe()

          Python       Math       DBMS
count   4.000000   4.000000   4.000000
mean   79.500000  85.750000  81.500000
std    11.676187  10.904892  10.661457
min    65.000000  70.000000  68.000000
25%    73.250000  83.500000  75.500000
50%    80.500000  89.000000  83.500000
75%    86.750000  91.250000  89.500000
max    92.000000  95.000000  91.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      str
 1   Python   4 non-null      int64
 2   Math     4 non-null      int64
 3   DBMS     4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 281.0 bytes

In [13]:
df["Python"]

0    85
1    76
2    65
3    92
Name: Python, dtype: int64

In [14]:
df[df["Python"] > 80]

  Student  Python  Math  DBMS
0   Aarav      85    90    78
3   Priya      92    95    89

In [15]:
df[(df["Python"] > 80) & (df["Math"] > 90)]

  Student  Python  Math  DBMS
3   Priya      92    95    89

In [19]:
df[(df["Python"]>80) | (df["Math"]>90 )]

  Student  Python  Math  DBMS
0   Aarav      85    90    78
3   Priya      92    95    89

In [20]:
df.loc[:, ["Student", "Python"]]

  Student  Python
0   Aarav      85
1  Ananya      76
2   Rahul      65
3   Priya      92

In [21]:
df.iloc[3, 3]

np.int64(89)

In [24]:
df.iloc[:, 2]

0    90
1    88
2    70
3    95
Name: Math, dtype: int64

In [26]:
df.iloc[0:1]

  Student  Python  Math  DBMS
0   Aarav      85    90    78

In [29]:
df.loc[:,["Student", "DBMS"]]

  Student  DBMS
0   Aarav    78
1  Ananya    91
2   Rahul    68
3   Priya    89

In [35]:
df.iloc[2]

Student    Rahul
Python        65
Math          70
DBMS          68
Name: 2, dtype: object

In [41]:
df.iloc[:,3]

0    78
1    91
2    68
3    89
Name: DBMS, dtype: int64

In [44]:
df.iloc[3]

Student    Priya
Python        92
Math          95
DBMS          89
Name: 3, dtype: object

In [46]:
df["Total"] = df["Python"] + df["Math"] + df["DBMS"]
print(df)

  Student  Python  Math  DBMS  Total
0   Aarav      85    90    78    253
1  Ananya      76    88    91    255
2   Rahul      65    70    68    203
3   Priya      92    95    89    276

In [48]:
df["Bonus"]=df["Python"]+5

In [49]:
df.loc[2, "Python"] = 75

In [50]:
df.loc[df["Python"] < 70, "Python"] += 5

In [51]:
df.isnull()

   Student  Python   Math   DBMS  Total  Bonus
0    False   False  False  False  False  False
1    False   False  False  False  False  False
2    False   False  False  False  False  False
3    False   False  False  False  False  False

In [52]:
df.isnull().sum

<bound method DataFrame.sum of    Student  Python   Math   DBMS  Total  Bonus
0    False   False  False  False  False  False
1    False   False  False  False  False  False
2    False   False  False  False  False  False
3    False   False  False  False  False  False>

In [60]:
df=pd.read_csv("student.csv")

In [71]:
df.head()

  Student  Python  Math  DBMS  Attendance  Total
0   Aarav      85  90.0  78.0        95.0  253.0
1  Ananya      76  88.0  91.0        90.0  255.0
2   Rahul      65   NaN  68.0        85.0    NaN
3   Priya      92  95.0  89.0         NaN  276.0
4   Arjun      58  60.0   NaN        80.0    NaN

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     6 non-null      str
 1   Python      6 non-null      int64
 2   Math        5 non-null      float64
 3   DBMS        5 non-null      float64
 4   Attendance  5 non-null      float64
 5   Total       4 non-null      float64
dtypes: float64(4), int64(1), str(1)
memory usage: 451.0 bytes

In [65]:
print(df["Math"].unique())
print(df["DBMS"].unique())
print(df["Attendance"].unique())

<ArrowStringArray>
['90', '88', '    NaN', '95', '60', '79']
Length: 6, dtype: str
<ArrowStringArray>
['78', '91', '68', '89', '    NaN', '85']
Length: 6, dtype: str
<ArrowStringArray>
['95', '90', '85', '    NaN', '80', '92']
Length: 6, dtype: str

In [66]:
df["Math"] = pd.to_numeric(df["Math"], errors="coerce")
df["DBMS"] = pd.to_numeric(df["DBMS"], errors="coerce")
df["Attendance"] = pd.to_numeric(df["Attendance"], errors="coerce")

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     6 non-null      str
 1   Python      6 non-null      int64
 2   Math        5 non-null      float64
 3   DBMS        5 non-null      float64
 4   Attendance  5 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 403.0 bytes

In [69]:
df["Total"] = df["Python"] + df["Math"] + df["DBMS"]
df

  Student  Python  Math  DBMS  Attendance  Total
0   Aarav      85  90.0  78.0        95.0  253.0
1  Ananya      76  88.0  91.0        90.0  255.0
2   Rahul      65   NaN  68.0        85.0    NaN
3   Priya      92  95.0  89.0         NaN  276.0
4   Arjun      58  60.0   NaN        80.0    NaN
5   Sneha      81  79.0  85.0        92.0  245.0

In [70]:
df.head()

  Student  Python  Math  DBMS  Attendance  Total
0   Aarav      85  90.0  78.0        95.0  253.0
1  Ananya      76  88.0  91.0        90.0  255.0
2   Rahul      65   NaN  68.0        85.0    NaN
3   Priya      92  95.0  89.0         NaN  276.0
4   Arjun      58  60.0   NaN        80.0    NaN

In [73]:
df["Math"]=df["Math"].fillna(df["Math"].mean())

In [74]:
df["DBMS"]=df["DBMS"].fillna(df["DBMS"].mean())

In [75]:
df["Attendance"]=df["Attendance"].fillna(df["Attendance"].mean())

In [78]:
df["Total"]=df["Python"]+df["Math"]+df["DBMS"]

In [79]:
df

  Student  Python  Math  DBMS  Attendance  Total
0   Aarav      85  90.0  78.0        95.0  253.0
1  Ananya      76  88.0  91.0        90.0  255.0
2   Rahul      65  82.4  68.0        85.0  215.4
3   Priya      92  95.0  89.0        88.4  276.0
4   Arjun      58  60.0  82.2        80.0  200.2
5   Sneha      81  79.0  85.0        92.0  245.0