In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Sales.csv")

In [3]:
df.head()

     City   Product  Sales
0    Pune    Laptop  50000
1  Mumbai     Mouse    800
2    Pune    Laptop  52000
3   Delhi  Keyboard   1500
4    Pune     Mouse    900

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   City     9 non-null      str
 1   Product  9 non-null      str
 2   Sales    9 non-null      int64
dtypes: int64(1), str(2)
memory usage: 447.0 bytes

In [5]:
df["City"].value_counts()

City
Pune      4
Mumbai    3
Delhi     2
Name: count, dtype: int64

In [6]:
df.value_counts()

City    Product   Sales
Pune    Laptop    50000    1
Mumbai  Mouse     800      1
Pune    Laptop    52000    1
Delhi   Keyboard  1500     1
Pune    Mouse     900      1
Mumbai  Laptop    51000    1
Delhi   Laptop    49000    1
Pune    Keyboard  1600     1
Mumbai  Mouse     850      1
Name: count, dtype: int64

In [8]:
df["City"].unique()

<ArrowStringArray>
['Pune', 'Mumbai', 'Delhi']
Length: 3, dtype: str

In [10]:
df["City"].nunique()

3

In [11]:
df.head()

     City   Product  Sales
0    Pune    Laptop  50000
1  Mumbai     Mouse    800
2    Pune    Laptop  52000
3   Delhi  Keyboard   1500
4    Pune     Mouse    900

In [13]:
total_city_sum=df.groupby("City")["Sales"].sum()
print(total_city_sum)

City
Delhi      50500
Mumbai     52650
Pune      104500
Name: Sales, dtype: int64

In [15]:
Product_sales=df.groupby("Product")["Sales"].sum()
print(Product_sales)

Product
Keyboard      3100
Laptop      202000
Mouse         2550
Name: Sales, dtype: int64

In [17]:
product_max=df.groupby("Product")["Sales"].max()
print(Product_sales)

Product
Keyboard      3100
Laptop      202000
Mouse         2550
Name: Sales, dtype: int64

In [22]:
count_city=df["City"].count
print(count_city)

<bound method Series.count of 0      Pune
1    Mumbai
2      Pune
3     Delhi
4      Pune
5    Mumbai
6     Delhi
7      Pune
8    Mumbai
Name: City, dtype: str>

In [24]:
df["City"].nunique()

3

In [30]:
count_city=df.groupby("City")["Sales"].count()
print(count_city)

City
Delhi     2
Mumbai    3
Pune      4
Name: Sales, dtype: int64