In [2]:
import pandas as pd

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Order_ID":[101,102,103,104,105,106,107,108,109,110],
    "City":["Pune","Mumbai","Pune","Delhi","Mumbai","Delhi","Pune","Mumbai","Delhi","Pune"],
    "Category":["Laptop","Mouse","Laptop","Keyboard","Laptop","Mouse","Keyboard","Mouse","Laptop","Laptop"],
    "Sales":[50000,800,52000,1500,51000,900,1600,850,np.nan,49000],
    "Quantity":[2,5,2,3,2,4,3,np.nan,2,2],
    "Rating":[4.8,4.2,4.9,4.1,4.7,4.0,np.nan,4.3,4.6,4.9]
})

print(df)

   Order_ID    City  Category    Sales  Quantity  Rating
0       101    Pune    Laptop  50000.0       2.0     4.8
1       102  Mumbai     Mouse    800.0       5.0     4.2
2       103    Pune    Laptop  52000.0       2.0     4.9
3       104   Delhi  Keyboard   1500.0       3.0     4.1
4       105  Mumbai    Laptop  51000.0       2.0     4.7
5       106   Delhi     Mouse    900.0       4.0     4.0
6       107    Pune  Keyboard   1600.0       3.0     NaN
7       108  Mumbai     Mouse    850.0       NaN     4.3
8       109   Delhi    Laptop      NaN       2.0     4.6
9       110    Pune    Laptop  49000.0       2.0     4.9

In [4]:
df.head()

   Order_ID    City  Category    Sales  Quantity  Rating
0       101    Pune    Laptop  50000.0       2.0     4.8
1       102  Mumbai     Mouse    800.0       5.0     4.2
2       103    Pune    Laptop  52000.0       2.0     4.9
3       104   Delhi  Keyboard   1500.0       3.0     4.1
4       105  Mumbai    Laptop  51000.0       2.0     4.7

In [5]:
df.shape

(10, 6)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  10 non-null     int64
 1   City      10 non-null     str
 2   Category  10 non-null     str
 3   Sales     9 non-null      float64
 4   Quantity  9 non-null      float64
 5   Rating    9 non-null      float64
dtypes: float64(3), int64(1), str(2)
memory usage: 722.0 bytes

In [7]:
df.dtypes

Order_ID      int64
City            str
Category        str
Sales       float64
Quantity    float64
Rating      float64
dtype: object

In [8]:
df.groupby("City")["Sales"].sum().idxmax()

'Pune'

In [9]:
df.groupby("Category")["Sales"].mean().idxmin()

'Mouse'

In [10]:
df.groupby("City")["Quantity"].sum().idxmax()

'Delhi'

In [11]:
def categ(salary):
    if salary >= 70000:
        return 10000
    else:
        return 5000

In [12]:
def result(mark):
    if mark >= 40:
        return "Pass"
    else:
        return "Fail"

In [13]:
df.rename(columns={"Category": "Categorys"})

   Order_ID    City Categorys    Sales  Quantity  Rating
0       101    Pune    Laptop  50000.0       2.0     4.8
1       102  Mumbai     Mouse    800.0       5.0     4.2
2       103    Pune    Laptop  52000.0       2.0     4.9
3       104   Delhi  Keyboard   1500.0       3.0     4.1
4       105  Mumbai    Laptop  51000.0       2.0     4.7
5       106   Delhi     Mouse    900.0       4.0     4.0
6       107    Pune  Keyboard   1600.0       3.0     NaN
7       108  Mumbai     Mouse    850.0       NaN     4.3
8       109   Delhi    Laptop      NaN       2.0     4.6
9       110    Pune    Laptop  49000.0       2.0     4.9

In [14]:
df["City"].str.lower()

0      pune
1    mumbai
2      pune
3     delhi
4    mumbai
5     delhi
6      pune
7    mumbai
8     delhi
9      pune
Name: City, dtype: str

In [15]:
df[df["City"].str.contains("Pune", case=False)]      #it does not see case it returns every row which contain pune without looking case

   Order_ID  City  Category    Sales  Quantity  Rating
0       101  Pune    Laptop  50000.0       2.0     4.8
2       103  Pune    Laptop  52000.0       2.0     4.9
6       107  Pune  Keyboard   1600.0       3.0     NaN
9       110  Pune    Laptop  49000.0       2.0     4.9

In [18]:
df["Sales_Avg"] = df.groupby("Category")["Sales"].transform("mean")

df["Sales_Avg"]

0    50500.0
1      850.0
2    50500.0
3     1550.0
4    50500.0
5      850.0
6     1550.0
7      850.0
8    50500.0
9    50500.0
Name: Sales_Avg, dtype: float64

In [19]:
df

   Order_ID    City  Category    Sales  Quantity  Rating  Dept_Avg  Sales_Avg
0       101    Pune    Laptop  50000.0       2.0     4.8   50500.0    50500.0
1       102  Mumbai     Mouse    800.0       5.0     4.2     850.0      850.0
2       103    Pune    Laptop  52000.0       2.0     4.9   50500.0    50500.0
3       104   Delhi  Keyboard   1500.0       3.0     4.1    1550.0     1550.0
4       105  Mumbai    Laptop  51000.0       2.0     4.7   50500.0    50500.0
5       106   Delhi     Mouse    900.0       4.0     4.0     850.0      850.0
6       107    Pune  Keyboard   1600.0       3.0     NaN    1550.0     1550.0
7       108  Mumbai     Mouse    850.0       NaN     4.3     850.0      850.0
8       109   Delhi    Laptop      NaN       2.0     4.6   50500.0    50500.0
9       110    Pune    Laptop  49000.0       2.0     4.9   50500.0    50500.0

In [20]:
df.drop(Dept_Avg)

NameError: name 'Dept_Avg' is not defined